version: '3.8'

services:

  api:
    build:
      context: ./pos-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pos_db
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3001
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  postgres_data:
    driver: local