name: pos-project
services:

  api:
    build:
      context: ./pos-api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./pos-api:/app
  web:
    build:
      context: ./pos-web
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3001
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - ./pos-web:/app
