apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Chart.Name}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
data:
  NODE_ENV: {{ .Values.configMap.NODE_ENV | quote }}
  HLAB_PORT: {{ .Values.configMap.HLAB_PORT | quote }}

