# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: {{ .Chart.Name }}
#   labels:
#     app: {{ .Chart.Name }}
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: {{ .Chart.Name }}
#   minReplicas: {{ .Values.hpa.minReplicas }}
#   maxReplicas: {{ .Values.hpa.maxReplicas }}
#   targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
