apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Chart.Name}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: opaque
stringData:
  JWT_SECRET: {{ .Values.secretMap.JWT_SECRET | quote }}
  POSTGRES_HOST:  {{ .Values.secretMap.POSTGRES_HOST | quote }}
  POSTGRES_DB:  {{ .Values.secretMap.POSTGRES_DB | quote }}
  POSTGRES_USER:  {{ .Values.secretMap.POSTGRES_USER | quote }}
  POSTGRES_PORT:  {{ .Values.secretMap.POSTGRES_PORT | quote }}
  POSTGRES_PASSWORD:  {{ .Values.secretMap.POSTGRES_PASSWORD | quote }}

  GOOGLE_CLIENT_ID: {{ .Values.secretMap.JWT_SECRET | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secretMap.JWT_SECRET | quote }}
  GOOGLE_REDIRECT_URI: {{ .Values.secretMap.JWT_SECRET | quote }}

  GOOGLE_ACCESS_TOKEN: {{ .Values.secretMap.JWT_SECRET | quote }}
  GOOGLE_REFRESH_TOKEN: {{ .Values.secretMap.JWT_SECRET | quote }}
  BACKEND_URL: {{ .Values.secretMap.JWT_SECRET | quote }}


